/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Chunk2Master_CONSTANTS_H
#define Chunk2Master_CONSTANTS_H

#include "Chunk2Master_types.h"

namespace GFS {

class Chunk2MasterConstants {
 public:
  Chunk2MasterConstants();

};

extern const Chunk2MasterConstants g_Chunk2Master_constants;

} // namespace

#endif
