/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ChunkServer_constants.h"

namespace GFS {

const ChunkServerConstants g_ChunkServer_constants;

ChunkServerConstants::ChunkServerConstants() {
}

} // namespace

