/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ChunkServer_CONSTANTS_H
#define ChunkServer_CONSTANTS_H

#include "ChunkServer_types.h"

namespace GFS {

class ChunkServerConstants {
 public:
  ChunkServerConstants();

};

extern const ChunkServerConstants g_ChunkServer_constants;

} // namespace

#endif
