/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ChunkServer_H
#define ChunkServer_H

#include <thrift/TDispatchProcessor.h>
#include "ChunkServer_types.h"

namespace GFS {

class ChunkServerIf {
 public:
  virtual ~ChunkServerIf() {}
  virtual int32_t open(const std::string& path, const int32_t oflag, const int32_t mode) = 0;
  virtual int32_t close(const int32_t fd) = 0;
  virtual int64_t write(const int32_t fd, const std::string& buf, const int32_t count) = 0;
  virtual void read(ReadResult& _return, const int32_t fd, const int32_t count) = 0;
};

class ChunkServerIfFactory {
 public:
  typedef ChunkServerIf Handler;

  virtual ~ChunkServerIfFactory() {}

  virtual ChunkServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ChunkServerIf* /* handler */) = 0;
};

class ChunkServerIfSingletonFactory : virtual public ChunkServerIfFactory {
 public:
  ChunkServerIfSingletonFactory(const boost::shared_ptr<ChunkServerIf>& iface) : iface_(iface) {}
  virtual ~ChunkServerIfSingletonFactory() {}

  virtual ChunkServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ChunkServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<ChunkServerIf> iface_;
};

class ChunkServerNull : virtual public ChunkServerIf {
 public:
  virtual ~ChunkServerNull() {}
  int32_t open(const std::string& /* path */, const int32_t /* oflag */, const int32_t /* mode */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t close(const int32_t /* fd */) {
    int32_t _return = 0;
    return _return;
  }
  int64_t write(const int32_t /* fd */, const std::string& /* buf */, const int32_t /* count */) {
    int64_t _return = 0;
    return _return;
  }
  void read(ReadResult& /* _return */, const int32_t /* fd */, const int32_t /* count */) {
    return;
  }
};

typedef struct _ChunkServer_open_args__isset {
  _ChunkServer_open_args__isset() : path(false), oflag(false), mode(false) {}
  bool path;
  bool oflag;
  bool mode;
} _ChunkServer_open_args__isset;

class ChunkServer_open_args {
 public:

  ChunkServer_open_args() : path(), oflag(0), mode(0) {
  }

  virtual ~ChunkServer_open_args() throw() {}

  std::string path;
  int32_t oflag;
  int32_t mode;

  _ChunkServer_open_args__isset __isset;

  void __set_path(const std::string& val) {
    path = val;
  }

  void __set_oflag(const int32_t val) {
    oflag = val;
  }

  void __set_mode(const int32_t val) {
    mode = val;
  }

  bool operator == (const ChunkServer_open_args & rhs) const
  {
    if (!(path == rhs.path))
      return false;
    if (!(oflag == rhs.oflag))
      return false;
    if (!(mode == rhs.mode))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_open_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_open_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ChunkServer_open_pargs {
 public:


  virtual ~ChunkServer_open_pargs() throw() {}

  const std::string* path;
  const int32_t* oflag;
  const int32_t* mode;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_open_result__isset {
  _ChunkServer_open_result__isset() : success(false) {}
  bool success;
} _ChunkServer_open_result__isset;

class ChunkServer_open_result {
 public:

  ChunkServer_open_result() : success(0) {
  }

  virtual ~ChunkServer_open_result() throw() {}

  int32_t success;

  _ChunkServer_open_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const ChunkServer_open_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_open_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_open_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_open_presult__isset {
  _ChunkServer_open_presult__isset() : success(false) {}
  bool success;
} _ChunkServer_open_presult__isset;

class ChunkServer_open_presult {
 public:


  virtual ~ChunkServer_open_presult() throw() {}

  int32_t* success;

  _ChunkServer_open_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ChunkServer_close_args__isset {
  _ChunkServer_close_args__isset() : fd(false) {}
  bool fd;
} _ChunkServer_close_args__isset;

class ChunkServer_close_args {
 public:

  ChunkServer_close_args() : fd(0) {
  }

  virtual ~ChunkServer_close_args() throw() {}

  int32_t fd;

  _ChunkServer_close_args__isset __isset;

  void __set_fd(const int32_t val) {
    fd = val;
  }

  bool operator == (const ChunkServer_close_args & rhs) const
  {
    if (!(fd == rhs.fd))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_close_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_close_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ChunkServer_close_pargs {
 public:


  virtual ~ChunkServer_close_pargs() throw() {}

  const int32_t* fd;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_close_result__isset {
  _ChunkServer_close_result__isset() : success(false) {}
  bool success;
} _ChunkServer_close_result__isset;

class ChunkServer_close_result {
 public:

  ChunkServer_close_result() : success(0) {
  }

  virtual ~ChunkServer_close_result() throw() {}

  int32_t success;

  _ChunkServer_close_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const ChunkServer_close_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_close_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_close_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_close_presult__isset {
  _ChunkServer_close_presult__isset() : success(false) {}
  bool success;
} _ChunkServer_close_presult__isset;

class ChunkServer_close_presult {
 public:


  virtual ~ChunkServer_close_presult() throw() {}

  int32_t* success;

  _ChunkServer_close_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ChunkServer_write_args__isset {
  _ChunkServer_write_args__isset() : fd(false), buf(false), count(false) {}
  bool fd;
  bool buf;
  bool count;
} _ChunkServer_write_args__isset;

class ChunkServer_write_args {
 public:

  ChunkServer_write_args() : fd(0), buf(), count(0) {
  }

  virtual ~ChunkServer_write_args() throw() {}

  int32_t fd;
  std::string buf;
  int32_t count;

  _ChunkServer_write_args__isset __isset;

  void __set_fd(const int32_t val) {
    fd = val;
  }

  void __set_buf(const std::string& val) {
    buf = val;
  }

  void __set_count(const int32_t val) {
    count = val;
  }

  bool operator == (const ChunkServer_write_args & rhs) const
  {
    if (!(fd == rhs.fd))
      return false;
    if (!(buf == rhs.buf))
      return false;
    if (!(count == rhs.count))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_write_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_write_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ChunkServer_write_pargs {
 public:


  virtual ~ChunkServer_write_pargs() throw() {}

  const int32_t* fd;
  const std::string* buf;
  const int32_t* count;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_write_result__isset {
  _ChunkServer_write_result__isset() : success(false) {}
  bool success;
} _ChunkServer_write_result__isset;

class ChunkServer_write_result {
 public:

  ChunkServer_write_result() : success(0) {
  }

  virtual ~ChunkServer_write_result() throw() {}

  int64_t success;

  _ChunkServer_write_result__isset __isset;

  void __set_success(const int64_t val) {
    success = val;
  }

  bool operator == (const ChunkServer_write_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_write_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_write_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_write_presult__isset {
  _ChunkServer_write_presult__isset() : success(false) {}
  bool success;
} _ChunkServer_write_presult__isset;

class ChunkServer_write_presult {
 public:


  virtual ~ChunkServer_write_presult() throw() {}

  int64_t* success;

  _ChunkServer_write_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _ChunkServer_read_args__isset {
  _ChunkServer_read_args__isset() : fd(false), count(false) {}
  bool fd;
  bool count;
} _ChunkServer_read_args__isset;

class ChunkServer_read_args {
 public:

  ChunkServer_read_args() : fd(0), count(0) {
  }

  virtual ~ChunkServer_read_args() throw() {}

  int32_t fd;
  int32_t count;

  _ChunkServer_read_args__isset __isset;

  void __set_fd(const int32_t val) {
    fd = val;
  }

  void __set_count(const int32_t val) {
    count = val;
  }

  bool operator == (const ChunkServer_read_args & rhs) const
  {
    if (!(fd == rhs.fd))
      return false;
    if (!(count == rhs.count))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_read_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_read_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ChunkServer_read_pargs {
 public:


  virtual ~ChunkServer_read_pargs() throw() {}

  const int32_t* fd;
  const int32_t* count;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_read_result__isset {
  _ChunkServer_read_result__isset() : success(false) {}
  bool success;
} _ChunkServer_read_result__isset;

class ChunkServer_read_result {
 public:

  ChunkServer_read_result() {
  }

  virtual ~ChunkServer_read_result() throw() {}

  ReadResult success;

  _ChunkServer_read_result__isset __isset;

  void __set_success(const ReadResult& val) {
    success = val;
  }

  bool operator == (const ChunkServer_read_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ChunkServer_read_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ChunkServer_read_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ChunkServer_read_presult__isset {
  _ChunkServer_read_presult__isset() : success(false) {}
  bool success;
} _ChunkServer_read_presult__isset;

class ChunkServer_read_presult {
 public:


  virtual ~ChunkServer_read_presult() throw() {}

  ReadResult* success;

  _ChunkServer_read_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ChunkServerClient : virtual public ChunkServerIf {
 public:
  ChunkServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  ChunkServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  int32_t open(const std::string& path, const int32_t oflag, const int32_t mode);
  void send_open(const std::string& path, const int32_t oflag, const int32_t mode);
  int32_t recv_open();
  int32_t close(const int32_t fd);
  void send_close(const int32_t fd);
  int32_t recv_close();
  int64_t write(const int32_t fd, const std::string& buf, const int32_t count);
  void send_write(const int32_t fd, const std::string& buf, const int32_t count);
  int64_t recv_write();
  void read(ReadResult& _return, const int32_t fd, const int32_t count);
  void send_read(const int32_t fd, const int32_t count);
  void recv_read(ReadResult& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ChunkServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<ChunkServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ChunkServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_open(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_close(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_write(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_read(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ChunkServerProcessor(boost::shared_ptr<ChunkServerIf> iface) :
    iface_(iface) {
    processMap_["open"] = &ChunkServerProcessor::process_open;
    processMap_["close"] = &ChunkServerProcessor::process_close;
    processMap_["write"] = &ChunkServerProcessor::process_write;
    processMap_["read"] = &ChunkServerProcessor::process_read;
  }

  virtual ~ChunkServerProcessor() {}
};

class ChunkServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ChunkServerProcessorFactory(const ::boost::shared_ptr< ChunkServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< ChunkServerIfFactory > handlerFactory_;
};

class ChunkServerMultiface : virtual public ChunkServerIf {
 public:
  ChunkServerMultiface(std::vector<boost::shared_ptr<ChunkServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ChunkServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<ChunkServerIf> > ifaces_;
  ChunkServerMultiface() {}
  void add(boost::shared_ptr<ChunkServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  int32_t open(const std::string& path, const int32_t oflag, const int32_t mode) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->open(path, oflag, mode);
    }
    return ifaces_[i]->open(path, oflag, mode);
  }

  int32_t close(const int32_t fd) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->close(fd);
    }
    return ifaces_[i]->close(fd);
  }

  int64_t write(const int32_t fd, const std::string& buf, const int32_t count) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->write(fd, buf, count);
    }
    return ifaces_[i]->write(fd, buf, count);
  }

  void read(ReadResult& _return, const int32_t fd, const int32_t count) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->read(_return, fd, count);
    }
    ifaces_[i]->read(_return, fd, count);
    return;
  }

};

} // namespace

#endif
