/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Chunk2Master_constants.h"

namespace GFS {

const Chunk2MasterConstants g_Chunk2Master_constants;

Chunk2MasterConstants::Chunk2MasterConstants() {
}

} // namespace

