/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Client2Chunk_CONSTANTS_H
#define Client2Chunk_CONSTANTS_H

#include "Client2Chunk_types.h"

namespace GFS {

class Client2ChunkConstants {
 public:
  Client2ChunkConstants();

};

extern const Client2ChunkConstants g_Client2Chunk_constants;

} // namespace

#endif
