/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Client2Master_TYPES_H
#define Client2Master_TYPES_H

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>


namespace GFS {

typedef struct _ReadResult__isset {
  _ReadResult__isset() : buf(false), count(false) {}
  bool buf;
  bool count;
} _ReadResult__isset;

class ReadResult {
 public:

  static const char* ascii_fingerprint; // = "1CCCF6FC31CFD1D61BBBB1BAF3590620";
  static const uint8_t binary_fingerprint[16]; // = {0x1C,0xCC,0xF6,0xFC,0x31,0xCF,0xD1,0xD6,0x1B,0xBB,0xB1,0xBA,0xF3,0x59,0x06,0x20};

  ReadResult() : buf(), count(0) {
  }

  virtual ~ReadResult() throw() {}

  std::string buf;
  int64_t count;

  _ReadResult__isset __isset;

  void __set_buf(const std::string& val) {
    buf = val;
  }

  void __set_count(const int64_t val) {
    count = val;
  }

  bool operator == (const ReadResult & rhs) const
  {
    if (!(buf == rhs.buf))
      return false;
    if (!(count == rhs.count))
      return false;
    return true;
  }
  bool operator != (const ReadResult &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ReadResult & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(ReadResult &a, ReadResult &b);

typedef struct _FileInfo__isset {
  _FileInfo__isset() : ipAddr(false), uuid(false), fd(false) {}
  bool ipAddr;
  bool uuid;
  bool fd;
} _FileInfo__isset;

class FileInfo {
 public:

  static const char* ascii_fingerprint; // = "343DA57F446177400B333DC49B037B0C";
  static const uint8_t binary_fingerprint[16]; // = {0x34,0x3D,0xA5,0x7F,0x44,0x61,0x77,0x40,0x0B,0x33,0x3D,0xC4,0x9B,0x03,0x7B,0x0C};

  FileInfo() : ipAddr(), uuid(), fd(0) {
  }

  virtual ~FileInfo() throw() {}

  std::string ipAddr;
  std::string uuid;
  int32_t fd;

  _FileInfo__isset __isset;

  void __set_ipAddr(const std::string& val) {
    ipAddr = val;
  }

  void __set_uuid(const std::string& val) {
    uuid = val;
  }

  void __set_fd(const int32_t val) {
    fd = val;
  }

  bool operator == (const FileInfo & rhs) const
  {
    if (!(ipAddr == rhs.ipAddr))
      return false;
    if (!(uuid == rhs.uuid))
      return false;
    if (!(fd == rhs.fd))
      return false;
    return true;
  }
  bool operator != (const FileInfo &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const FileInfo & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

void swap(FileInfo &a, FileInfo &b);

} // namespace

#endif
