// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FileOpManager.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::GFS;

class FileOpManagerHandler : virtual public FileOpManagerIf {
 public:
  FileOpManagerHandler() {
    // Your initialization goes here
  }

  int32_t open(const std::string& path, const int32_t oflag, const int32_t mode) {
    // Your implementation goes here
    printf("open\n");
  }

  int32_t close(const int32_t fd) {
    // Your implementation goes here
    printf("close\n");
  }

  void askNewChunk(FileInfo& _return, const int32_t fd) {
    // Your implementation goes here
    printf("askNewChunk\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FileOpManagerHandler> handler(new FileOpManagerHandler());
  shared_ptr<TProcessor> processor(new FileOpManagerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

