// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "FileIO.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::GFS;

class FileIOHandler : virtual public FileIOIf {
 public:
  FileIOHandler() {
    // Your initialization goes here
  }

  int64_t write(const int32_t fd, const std::string& buf) {
    // Your implementation goes here
    printf("write\n");
  }

  void read(ReadResult& _return, const int32_t fd, const int64_t count) {
    // Your implementation goes here
    printf("read\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<FileIOHandler> handler(new FileIOHandler());
  shared_ptr<TProcessor> processor(new FileIOProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

