/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MasterServer_H
#define MasterServer_H

#include <thrift/TDispatchProcessor.h>
#include "MasterServer_types.h"

namespace GFS {

class MasterServerIf {
 public:
  virtual ~MasterServerIf() {}
  virtual bool registerChunkServer(const std::string& ipAddr, const int64_t availMem) = 0;
  virtual void unregisterChunkServer(const std::string& ipAddr) = 0;
  virtual bool heartBeat(const ChunkServerInfo& info) = 0;
  virtual int32_t open(const std::string& path, const int32_t oflag, const int32_t mode) = 0;
  virtual int32_t close(const int32_t fd) = 0;
  virtual void askNewChunk(FileInfo& _return, const int32_t fd) = 0;
};

class MasterServerIfFactory {
 public:
  typedef MasterServerIf Handler;

  virtual ~MasterServerIfFactory() {}

  virtual MasterServerIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(MasterServerIf* /* handler */) = 0;
};

class MasterServerIfSingletonFactory : virtual public MasterServerIfFactory {
 public:
  MasterServerIfSingletonFactory(const boost::shared_ptr<MasterServerIf>& iface) : iface_(iface) {}
  virtual ~MasterServerIfSingletonFactory() {}

  virtual MasterServerIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(MasterServerIf* /* handler */) {}

 protected:
  boost::shared_ptr<MasterServerIf> iface_;
};

class MasterServerNull : virtual public MasterServerIf {
 public:
  virtual ~MasterServerNull() {}
  bool registerChunkServer(const std::string& /* ipAddr */, const int64_t /* availMem */) {
    bool _return = false;
    return _return;
  }
  void unregisterChunkServer(const std::string& /* ipAddr */) {
    return;
  }
  bool heartBeat(const ChunkServerInfo& /* info */) {
    bool _return = false;
    return _return;
  }
  int32_t open(const std::string& /* path */, const int32_t /* oflag */, const int32_t /* mode */) {
    int32_t _return = 0;
    return _return;
  }
  int32_t close(const int32_t /* fd */) {
    int32_t _return = 0;
    return _return;
  }
  void askNewChunk(FileInfo& /* _return */, const int32_t /* fd */) {
    return;
  }
};

typedef struct _MasterServer_registerChunkServer_args__isset {
  _MasterServer_registerChunkServer_args__isset() : ipAddr(false), availMem(false) {}
  bool ipAddr;
  bool availMem;
} _MasterServer_registerChunkServer_args__isset;

class MasterServer_registerChunkServer_args {
 public:

  MasterServer_registerChunkServer_args() : ipAddr(), availMem(0) {
  }

  virtual ~MasterServer_registerChunkServer_args() throw() {}

  std::string ipAddr;
  int64_t availMem;

  _MasterServer_registerChunkServer_args__isset __isset;

  void __set_ipAddr(const std::string& val) {
    ipAddr = val;
  }

  void __set_availMem(const int64_t val) {
    availMem = val;
  }

  bool operator == (const MasterServer_registerChunkServer_args & rhs) const
  {
    if (!(ipAddr == rhs.ipAddr))
      return false;
    if (!(availMem == rhs.availMem))
      return false;
    return true;
  }
  bool operator != (const MasterServer_registerChunkServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_registerChunkServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterServer_registerChunkServer_pargs {
 public:


  virtual ~MasterServer_registerChunkServer_pargs() throw() {}

  const std::string* ipAddr;
  const int64_t* availMem;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_registerChunkServer_result__isset {
  _MasterServer_registerChunkServer_result__isset() : success(false) {}
  bool success;
} _MasterServer_registerChunkServer_result__isset;

class MasterServer_registerChunkServer_result {
 public:

  MasterServer_registerChunkServer_result() : success(0) {
  }

  virtual ~MasterServer_registerChunkServer_result() throw() {}

  bool success;

  _MasterServer_registerChunkServer_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const MasterServer_registerChunkServer_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterServer_registerChunkServer_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_registerChunkServer_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_registerChunkServer_presult__isset {
  _MasterServer_registerChunkServer_presult__isset() : success(false) {}
  bool success;
} _MasterServer_registerChunkServer_presult__isset;

class MasterServer_registerChunkServer_presult {
 public:


  virtual ~MasterServer_registerChunkServer_presult() throw() {}

  bool* success;

  _MasterServer_registerChunkServer_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MasterServer_unregisterChunkServer_args__isset {
  _MasterServer_unregisterChunkServer_args__isset() : ipAddr(false) {}
  bool ipAddr;
} _MasterServer_unregisterChunkServer_args__isset;

class MasterServer_unregisterChunkServer_args {
 public:

  MasterServer_unregisterChunkServer_args() : ipAddr() {
  }

  virtual ~MasterServer_unregisterChunkServer_args() throw() {}

  std::string ipAddr;

  _MasterServer_unregisterChunkServer_args__isset __isset;

  void __set_ipAddr(const std::string& val) {
    ipAddr = val;
  }

  bool operator == (const MasterServer_unregisterChunkServer_args & rhs) const
  {
    if (!(ipAddr == rhs.ipAddr))
      return false;
    return true;
  }
  bool operator != (const MasterServer_unregisterChunkServer_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_unregisterChunkServer_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterServer_unregisterChunkServer_pargs {
 public:


  virtual ~MasterServer_unregisterChunkServer_pargs() throw() {}

  const std::string* ipAddr;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_heartBeat_args__isset {
  _MasterServer_heartBeat_args__isset() : info(false) {}
  bool info;
} _MasterServer_heartBeat_args__isset;

class MasterServer_heartBeat_args {
 public:

  MasterServer_heartBeat_args() {
  }

  virtual ~MasterServer_heartBeat_args() throw() {}

  ChunkServerInfo info;

  _MasterServer_heartBeat_args__isset __isset;

  void __set_info(const ChunkServerInfo& val) {
    info = val;
  }

  bool operator == (const MasterServer_heartBeat_args & rhs) const
  {
    if (!(info == rhs.info))
      return false;
    return true;
  }
  bool operator != (const MasterServer_heartBeat_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_heartBeat_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterServer_heartBeat_pargs {
 public:


  virtual ~MasterServer_heartBeat_pargs() throw() {}

  const ChunkServerInfo* info;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_heartBeat_result__isset {
  _MasterServer_heartBeat_result__isset() : success(false) {}
  bool success;
} _MasterServer_heartBeat_result__isset;

class MasterServer_heartBeat_result {
 public:

  MasterServer_heartBeat_result() : success(0) {
  }

  virtual ~MasterServer_heartBeat_result() throw() {}

  bool success;

  _MasterServer_heartBeat_result__isset __isset;

  void __set_success(const bool val) {
    success = val;
  }

  bool operator == (const MasterServer_heartBeat_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterServer_heartBeat_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_heartBeat_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_heartBeat_presult__isset {
  _MasterServer_heartBeat_presult__isset() : success(false) {}
  bool success;
} _MasterServer_heartBeat_presult__isset;

class MasterServer_heartBeat_presult {
 public:


  virtual ~MasterServer_heartBeat_presult() throw() {}

  bool* success;

  _MasterServer_heartBeat_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MasterServer_open_args__isset {
  _MasterServer_open_args__isset() : path(false), oflag(false), mode(false) {}
  bool path;
  bool oflag;
  bool mode;
} _MasterServer_open_args__isset;

class MasterServer_open_args {
 public:

  MasterServer_open_args() : path(), oflag(0), mode(0) {
  }

  virtual ~MasterServer_open_args() throw() {}

  std::string path;
  int32_t oflag;
  int32_t mode;

  _MasterServer_open_args__isset __isset;

  void __set_path(const std::string& val) {
    path = val;
  }

  void __set_oflag(const int32_t val) {
    oflag = val;
  }

  void __set_mode(const int32_t val) {
    mode = val;
  }

  bool operator == (const MasterServer_open_args & rhs) const
  {
    if (!(path == rhs.path))
      return false;
    if (!(oflag == rhs.oflag))
      return false;
    if (!(mode == rhs.mode))
      return false;
    return true;
  }
  bool operator != (const MasterServer_open_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_open_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterServer_open_pargs {
 public:


  virtual ~MasterServer_open_pargs() throw() {}

  const std::string* path;
  const int32_t* oflag;
  const int32_t* mode;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_open_result__isset {
  _MasterServer_open_result__isset() : success(false) {}
  bool success;
} _MasterServer_open_result__isset;

class MasterServer_open_result {
 public:

  MasterServer_open_result() : success(0) {
  }

  virtual ~MasterServer_open_result() throw() {}

  int32_t success;

  _MasterServer_open_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const MasterServer_open_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterServer_open_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_open_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_open_presult__isset {
  _MasterServer_open_presult__isset() : success(false) {}
  bool success;
} _MasterServer_open_presult__isset;

class MasterServer_open_presult {
 public:


  virtual ~MasterServer_open_presult() throw() {}

  int32_t* success;

  _MasterServer_open_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MasterServer_close_args__isset {
  _MasterServer_close_args__isset() : fd(false) {}
  bool fd;
} _MasterServer_close_args__isset;

class MasterServer_close_args {
 public:

  MasterServer_close_args() : fd(0) {
  }

  virtual ~MasterServer_close_args() throw() {}

  int32_t fd;

  _MasterServer_close_args__isset __isset;

  void __set_fd(const int32_t val) {
    fd = val;
  }

  bool operator == (const MasterServer_close_args & rhs) const
  {
    if (!(fd == rhs.fd))
      return false;
    return true;
  }
  bool operator != (const MasterServer_close_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_close_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterServer_close_pargs {
 public:


  virtual ~MasterServer_close_pargs() throw() {}

  const int32_t* fd;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_close_result__isset {
  _MasterServer_close_result__isset() : success(false) {}
  bool success;
} _MasterServer_close_result__isset;

class MasterServer_close_result {
 public:

  MasterServer_close_result() : success(0) {
  }

  virtual ~MasterServer_close_result() throw() {}

  int32_t success;

  _MasterServer_close_result__isset __isset;

  void __set_success(const int32_t val) {
    success = val;
  }

  bool operator == (const MasterServer_close_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterServer_close_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_close_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_close_presult__isset {
  _MasterServer_close_presult__isset() : success(false) {}
  bool success;
} _MasterServer_close_presult__isset;

class MasterServer_close_presult {
 public:


  virtual ~MasterServer_close_presult() throw() {}

  int32_t* success;

  _MasterServer_close_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _MasterServer_askNewChunk_args__isset {
  _MasterServer_askNewChunk_args__isset() : fd(false) {}
  bool fd;
} _MasterServer_askNewChunk_args__isset;

class MasterServer_askNewChunk_args {
 public:

  MasterServer_askNewChunk_args() : fd(0) {
  }

  virtual ~MasterServer_askNewChunk_args() throw() {}

  int32_t fd;

  _MasterServer_askNewChunk_args__isset __isset;

  void __set_fd(const int32_t val) {
    fd = val;
  }

  bool operator == (const MasterServer_askNewChunk_args & rhs) const
  {
    if (!(fd == rhs.fd))
      return false;
    return true;
  }
  bool operator != (const MasterServer_askNewChunk_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_askNewChunk_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class MasterServer_askNewChunk_pargs {
 public:


  virtual ~MasterServer_askNewChunk_pargs() throw() {}

  const int32_t* fd;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_askNewChunk_result__isset {
  _MasterServer_askNewChunk_result__isset() : success(false) {}
  bool success;
} _MasterServer_askNewChunk_result__isset;

class MasterServer_askNewChunk_result {
 public:

  MasterServer_askNewChunk_result() {
  }

  virtual ~MasterServer_askNewChunk_result() throw() {}

  FileInfo success;

  _MasterServer_askNewChunk_result__isset __isset;

  void __set_success(const FileInfo& val) {
    success = val;
  }

  bool operator == (const MasterServer_askNewChunk_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const MasterServer_askNewChunk_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const MasterServer_askNewChunk_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _MasterServer_askNewChunk_presult__isset {
  _MasterServer_askNewChunk_presult__isset() : success(false) {}
  bool success;
} _MasterServer_askNewChunk_presult__isset;

class MasterServer_askNewChunk_presult {
 public:


  virtual ~MasterServer_askNewChunk_presult() throw() {}

  FileInfo* success;

  _MasterServer_askNewChunk_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class MasterServerClient : virtual public MasterServerIf {
 public:
  MasterServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  MasterServerClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  bool registerChunkServer(const std::string& ipAddr, const int64_t availMem);
  void send_registerChunkServer(const std::string& ipAddr, const int64_t availMem);
  bool recv_registerChunkServer();
  void unregisterChunkServer(const std::string& ipAddr);
  void send_unregisterChunkServer(const std::string& ipAddr);
  bool heartBeat(const ChunkServerInfo& info);
  void send_heartBeat(const ChunkServerInfo& info);
  bool recv_heartBeat();
  int32_t open(const std::string& path, const int32_t oflag, const int32_t mode);
  void send_open(const std::string& path, const int32_t oflag, const int32_t mode);
  int32_t recv_open();
  int32_t close(const int32_t fd);
  void send_close(const int32_t fd);
  int32_t recv_close();
  void askNewChunk(FileInfo& _return, const int32_t fd);
  void send_askNewChunk(const int32_t fd);
  void recv_askNewChunk(FileInfo& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class MasterServerProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<MasterServerIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (MasterServerProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_registerChunkServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_unregisterChunkServer(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_heartBeat(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_open(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_close(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_askNewChunk(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  MasterServerProcessor(boost::shared_ptr<MasterServerIf> iface) :
    iface_(iface) {
    processMap_["registerChunkServer"] = &MasterServerProcessor::process_registerChunkServer;
    processMap_["unregisterChunkServer"] = &MasterServerProcessor::process_unregisterChunkServer;
    processMap_["heartBeat"] = &MasterServerProcessor::process_heartBeat;
    processMap_["open"] = &MasterServerProcessor::process_open;
    processMap_["close"] = &MasterServerProcessor::process_close;
    processMap_["askNewChunk"] = &MasterServerProcessor::process_askNewChunk;
  }

  virtual ~MasterServerProcessor() {}
};

class MasterServerProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  MasterServerProcessorFactory(const ::boost::shared_ptr< MasterServerIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< MasterServerIfFactory > handlerFactory_;
};

class MasterServerMultiface : virtual public MasterServerIf {
 public:
  MasterServerMultiface(std::vector<boost::shared_ptr<MasterServerIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~MasterServerMultiface() {}
 protected:
  std::vector<boost::shared_ptr<MasterServerIf> > ifaces_;
  MasterServerMultiface() {}
  void add(boost::shared_ptr<MasterServerIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  bool registerChunkServer(const std::string& ipAddr, const int64_t availMem) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->registerChunkServer(ipAddr, availMem);
    }
    return ifaces_[i]->registerChunkServer(ipAddr, availMem);
  }

  void unregisterChunkServer(const std::string& ipAddr) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->unregisterChunkServer(ipAddr);
    }
    ifaces_[i]->unregisterChunkServer(ipAddr);
  }

  bool heartBeat(const ChunkServerInfo& info) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->heartBeat(info);
    }
    return ifaces_[i]->heartBeat(info);
  }

  int32_t open(const std::string& path, const int32_t oflag, const int32_t mode) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->open(path, oflag, mode);
    }
    return ifaces_[i]->open(path, oflag, mode);
  }

  int32_t close(const int32_t fd) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->close(fd);
    }
    return ifaces_[i]->close(fd);
  }

  void askNewChunk(FileInfo& _return, const int32_t fd) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->askNewChunk(_return, fd);
    }
    ifaces_[i]->askNewChunk(_return, fd);
    return;
  }

};

} // namespace

#endif
