/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "MasterServer_constants.h"

namespace GFS {

const MasterServerConstants g_MasterServer_constants;

MasterServerConstants::MasterServerConstants() {
}

} // namespace

