/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef MasterServer_CONSTANTS_H
#define MasterServer_CONSTANTS_H

#include "MasterServer_types.h"

namespace GFS {

class MasterServerConstants {
 public:
  MasterServerConstants();

};

extern const MasterServerConstants g_MasterServer_constants;

} // namespace

#endif
