/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Client2Master_CONSTANTS_H
#define Client2Master_CONSTANTS_H

#include "Client2Master_types.h"

namespace GFS {

class Client2MasterConstants {
 public:
  Client2MasterConstants();

};

extern const Client2MasterConstants g_Client2Master_constants;

} // namespace

#endif
