/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Client2Master_constants.h"

namespace GFS {

const Client2MasterConstants g_Client2Master_constants;

Client2MasterConstants::Client2MasterConstants() {
}

} // namespace

