/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Client2Chunk_constants.h"

namespace GFS {

const Client2ChunkConstants g_Client2Chunk_constants;

Client2ChunkConstants::Client2ChunkConstants() {
}

} // namespace

