// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "ChunkServerManager.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::GFS;

class ChunkServerManagerHandler : virtual public ChunkServerManagerIf {
 public:
  ChunkServerManagerHandler() {
    // Your initialization goes here
  }

  bool registerChunkServer(const std::string& ipAddr, const int64_t availMem) {
    // Your implementation goes here
    printf("registerChunkServer\n");
  }

  void unregisterChunkServer(const std::string& ipAddr) {
    // Your implementation goes here
    printf("unregisterChunkServer\n");
  }

  bool heartBeat(const ChunkServerInfo& info) {
    // Your implementation goes here
    printf("heartBeat\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<ChunkServerManagerHandler> handler(new ChunkServerManagerHandler());
  shared_ptr<TProcessor> processor(new ChunkServerManagerProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

